Repository yunionio/pkg, pull requests merged in 2019-09, with the labels that each got.

#23 fix: 1. move util/errors/aggegrate to errors 2. version add short date string
  errors/aggregate.go
  errors/aggregate_test.go
  util/version/version.go
  util/version/version_test.go
Labels: approved, lgtm, size/XL

#24 fix: full iso time format支持变长的subSecond
  util/regutils/regutils.go
  util/regutils/regutils_test.go
  util/timeutils/timeutils.go
  util/timeutils/timeutils_test.go
Labels: approved, lgtm, size/M

#25 添加功能: gotypes.ConvertSliceElemType(), IPV4Prefix.Equals()
  gotypes/gotypes.go
  gotypes/gotypes_test.go
  util/netutils/netutils.go
Labels: approved, lgtm, size/L

#26 netutils: 改正IPV4Prefix.Equals()
  util/netutils/netutils.go
Labels: approved, lgtm, size/S

#27 fix: time reg not match negative time zone
  util/regutils/regutils.go
  util/regutils/regutils_test.go
Labels: approved, lgtm, size/S

#28 netutils equals bugfix
  util/netutils/netutils.go
Labels: approved, lgtm, size/XS

#29 netutils equals bugfix
  util/netutils/netutils.go
Labels: approved, lgtm, size/XS
