Repository yunionio/pkg, pull requests merged in 2019-04, with the labels that each got.

#6 remove stale helm pkg
  helm/doc.go
  helm/helm.go
  helm/install.go
  helm/kubernetes.go
  helm/repo.go
Labels: approved, lgtm, size/XXL

#8 Add FibonacciRetrier
  utils/fibonacci_retrier.go
  utils/fibonacci_retrier_test.go
Labels: approved, lgtm, size/L

#9 fix: trace panic when remote addr is empty
  trace/trace.go
Labels: approved, lgtm, size/XS

#10 fix: add function CamelSplitTokens to split tokens of camel-case varnames
  utils/utils.go
Labels: approved, lgtm, size/XS

#11 fix: truncatestring and interface2string
  util/stringutils/stringutils.go
  utils/utils.go
  utils/utils_test.go
Labels: approved, lgtm, size/M
