Repository yunionio/pkg, pull requests merged in 2019-12, with the labels that each got.

#42 reflectutils: ignore fields properly
  gotypes/deepcopy.go
  util/reflectutils/jsonfield.go
Labels: approved, lgtm, size/S

#43 refactor(reflectutils): Add StructFieldInfo Cache
  util/reflectutils/jsonfield.go
  util/reflectutils/jsonfield_test.go
Labels: approved, lgtm, size/L

#44 fix: Fix the bug in case of adding FieldInfoCache
  util/reflectutils/jsonfield.go
Labels: lgtm, size/M
