Repository yunionio/pkg, pull requests merged in 2019-10, with the labels that each got.

#30 Bugfix/yousong test
  .github/workflows/build-and-test.yaml
  util/fifoutils/fifoutils_test.go
Labels: approved, lgtm, size/M

#31 optimized: 导出GetPorts函数
  util/secrules/secrules.go
Labels: approved, lgtm, size/XS

#32 fix: 避免写log时直接传err时日志记录为{}
  util/stringutils/stringutils.go
  util/stringutils/stringutils_test.go
Labels: approved, lgtm, size/S
