Repository yunionio/pkg, pull requests merged in 2020-04, with the labels that each got.

#54 add errors.Errorf
  errors/errors.go
Labels: size/XS

#57 .github: increase shallow fetch depth to 8
  .github/workflows/build-and-test.yaml
Labels: approved, lgtm, size/XS

#55 Feature/yousong prettytable wrapline
  prettytable/prettytable.go
  prettytable/prettytable_test.go
Labels: size/L

#56 feature: add tag yunion:ambiguous-prefix support
  util/reflectutils/ambiguous.go
  util/reflectutils/jsonfield.go
  util/reflectutils/jsonfield_test.go
Labels: size/L

#58 fix: json name match rule backward compatble
  util/reflectutils/jsonfield.go
  util/reflectutils/jsonfield_test.go
Labels: size/M

#59 fix: make windows compatible
  prettytable/prettytable.go
  prettytable/termwidth_unix.go
  prettytable/termwidth_windows.go
Labels: approved, lgtm

#60 feature: windows termWidth
  prettytable/termwidth_windows.go
Labels: approved, lgtm, size/S
