Repository yunionio/pkg, pull requests merged in 2020-06, with the labels that each got.

#63 fix: 1. allow get all fields including ignored fields 2. fix set string bug
  gotypes/gotypes.go
  util/reflectutils/jsonfield.go
Labels: size/M

#64 new pretty table with try term width
  prettytable/prettytable.go
Labels: size/XS

#65 Bugfix/yousong bench camelsplit
  util/reflectutils/jsonfield.go
  util/reflectutils/reflectutils_test.go
  utils/utils.go
  utils/utils_test.go
Labels: lgtm, size/L
