Repository yunionio/pkg, pull requests merged in 2020-10, with the labels that each got.

#70 fix: 避免删除本地external_id为空的资源
  util/compare/compare.go
  util/compare/compare_test.go
Labels: approved, lgtm, size/L

#71 fix: set private prefixes
  util/netutils/netutils.go
Labels: approved, lgtm, size/M

#72 fix: set default private prefixes if no parameter given
  util/netutils/netutils.go
Labels: approved, lgtm, size/S

#73 fix: private prefxies may not initialized
  util/netutils/netutils.go
Labels: size/S
