Repository yunionio/pkg, pull requests merged in 2021-09, with the labels that each got.

#79 optimized: allow specified res function
  util/compare/compare.go
Labels: size/S, lgtm, approved

#80 feature: split csv line to string array
  utils/tags.go
  utils/tags_test.go
Labels: size/M

#81 update readme
  README.md
Labels: size/XS
